platform :ios, '12.0'
use_frameworks!

# workaround to avoid Xcode caching of Pods that requires
# Product -> Clean Build Folder after new Cordova plugins installed
# Requires CocoaPods 1.6 or newer
install! 'cocoapods', :disable_input_output_paths => true

def capacitor_pods
  pod 'Capacitor', :path => '../../node_modules/.pnpm/@capacitor+ios@3.4.3_@capacitor+core@3.4.3/node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../../node_modules/.pnpm/@capacitor+ios@3.4.3_@capacitor+core@3.4.3/node_modules/@capacitor/ios'
  pod 'CapacitorCommunityKeepAwake', :path => '../../node_modules/.pnpm/@capacitor-community+keep-awake@2.1.1_@capacitor+core@3.4.3/node_modules/@capacitor-community/keep-awake'
  pod 'CapacitorApp', :path => '../../node_modules/.pnpm/@capacitor+app@1.1.1_@capacitor+core@3.4.3/node_modules/@capacitor/app'
  pod 'CapacitorDevice', :path => '../../node_modules/.pnpm/@capacitor+device@1.1.2_@capacitor+core@3.4.3/node_modules/@capacitor/device'
  pod 'CapacitorHaptics', :path => '../../node_modules/.pnpm/@capacitor+haptics@1.1.4_@capacitor+core@3.4.3/node_modules/@capacitor/haptics'
  pod 'CapacitorKeyboard', :path => '../../node_modules/.pnpm/@capacitor+keyboard@1.2.2_@capacitor+core@3.4.3/node_modules/@capacitor/keyboard'
  pod 'CapacitorSplashScreen', :path => '../../node_modules/.pnpm/@capacitor+splash-screen@1.2.2_@capacitor+core@3.4.3/node_modules/@capacitor/splash-screen'
  pod 'CapacitorStatusBar', :path => '../../node_modules/.pnpm/@capacitor+status-bar@1.0.8_@capacitor+core@3.4.3/node_modules/@capacitor/status-bar'
  pod 'CapacitorStorage', :path => '../../node_modules/.pnpm/@capacitor+storage@1.2.5_@capacitor+core@3.4.3/node_modules/@capacitor/storage'
  pod 'CapacitorNativeAudio', :path => '../../node_modules/.pnpm/capacitor-native-audio@3.0.2_@capacitor+core@3.4.3/node_modules/capacitor-native-audio'
  pod 'CapacitorPurchases', :path => '../../node_modules/.pnpm/capacitor-purchases@1.0.3_@capacitor+core@3.4.3/node_modules/capacitor-purchases'
  pod 'CapacitorRateApp', :path => '../../node_modules/.pnpm/capacitor-rate-app@2.0.0_@capacitor+core@3.4.3/node_modules/capacitor-rate-app'
  pod 'CapacitorUpdater', :path => '../../node_modules/.pnpm/capacitor-updater@2.0.11_@capacitor+core@3.4.3/node_modules/capacitor-updater'
  pod 'CordovaPluginsStatic', :path => '../capacitor-cordova-ios-plugins'
end

target 'App' do
  capacitor_pods
  # Add your Pods here
end
