name: Build source code and send to Capgo

on:
  push:
    tags:
      - '*'
      
jobs:
  deploy:
    runs-on: ubuntu-latest
    name: "Build code and release"
    steps:
      - name: Check out
        uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.22.2
      - name: Install dependencies
        id: install_code
        run: pnpm i        
      - name: Lint
        id: lint_code
        run: pnpm lint:markup && pnpm lint:script
      - name: Test
        id: test_code
        run: pnpm test:run
      - name: Build
        id: build_code
        run: pnpm run build
      - name: Create Release
        id: create_release
        run: npx capgo upload -a ${{ secrets.CAPGO_TOKEN }} -c production
      

